name: updata-web-engineering

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: switch node version
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16.13.2
      - name: checkout
        uses: actions/checkout@v3.5.2
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: pull server-code
        run: |
          git clone https://github.com/Sensems/resource-server.git
          git checkout main
          sudo rm -rf ./resource-server/view/*
      - name: move web build to server view
        run: |
          sudo cp -rf ./resource-server-web/dist ./resource-server/view
          cd ./resource-server
          git commit -m 'update web project'
          git push
    
